version: '3.3'

services:
  frontend:
    build:
      context: ./GITHUB_ACTIONS_FRONTEND
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./GITHUB_ACTIONS_BACKEND
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_URL=mongodb+srv://huqfaqatali:852728,,!@cluster0.wapew1c.mongodb.net/

  production:
    build:
      context: ./GITHUB_ACTIONS_FRONTEND
      dockerfile: Dockerfile-new
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

#  zabbix-server:
#    image: zabbix/zabbix-server-mysql:latest
#    ports:
#      - "5500:10051"
#    environment:
#      - DB_SERVER_HOST=mysql
#      - MYSQL_DATABASE=zabbix
#      - MYSQL_USER=zabbix
#      - MYSQL_PASSWORD=zabbix_123
#      - MYSQL_ROOT_PASSWORD=root_password
#    depends_on:
#      - mysql

#  zabbix-web:
#    image: zabbix/zabbix-web-nginx-mysql:latest
#    ports:
#      - "4000:8080"
#    environment:
#      - DB_SERVER_HOST=mysql
#      - MYSQL_DATABASE=zabbix
#      - MYSQL_USER=zabbix
#      - MYSQL_PASSWORD=zabbix_123
#      - MYSQL_ROOT_PASSWORD=root_password
#    depends_on:
#      - mysql

#  mysql:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root_password
#      - MYSQL_DATABASE=zabbix
#      - MYSQL_USER=zabbix
#      - MYSQL_PASSWORD=zabbix_123
#    volumes:
#      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
